name: Build and test

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}      
      - name: Install pytorch
        run: |
          pip install torch torchvision
      - name: Install MMCV
        run: |
          pip install -U openmim
          mim install mmcv-full
      - name: Install MMGeneration
        run: |
          git clone https://github.com/open-mmlab/mmgeneration.git
          cd mmgeneration
          pip install -v -e .
          cd ..
          rm -rf mmgeneration
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .
      - name: Run the tests
        run: |
          python setup.py test
